/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/owner/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Страница предстоящих встреч: единый список бронирований по всем типам
         *     событий, отсортированный по start по возрастанию.
         */
        get: operations["OwnerBookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OwnerBookings_get"];
        put?: never;
        post?: never;
        /** @description Отмена встречи владельцем освобождает слот. */
        delete: operations["OwnerBookings_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Все типы событий владельца. */
        get: operations["OwnerEventTypes_list"];
        put?: never;
        /** @description Создать тип события. id задаёт владелец, он должен быть уникальным. */
        post: operations["OwnerEventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OwnerEventTypes_get"];
        put?: never;
        post?: never;
        /**
         * @description Удаление типа события не удаляет уже созданные бронирования:
         *     они остаются в списке встреч с сохранённым eventTypeTitle.
         */
        delete: operations["OwnerEventTypes_delete"];
        options?: never;
        head?: never;
        /** @description Изменение durationMinutes не пересчитывает уже созданные бронирования. */
        patch: operations["OwnerEventTypes_update"];
        trace?: never;
    };
    "/api/owner/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Профиль владельца, используемый админкой по умолчанию. */
        get: operations["OwnerProfile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать бронирование на выбранный слот.
         *     409 slot_taken — если время успели занять, пока гость заполнял форму.
         */
        post: operations["PublicBookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Экран подтверждения: гость открывает бронирование по ссылке с id. */
        get: operations["PublicBookings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Каталог: карточки «Выберите тип события». */
        get: operations["PublicEventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicEventTypes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/event-types/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Доступность по дням на всё окно записи — данные для месячной сетки
         *     календаря с подписями «сколько свободно».
         */
        get: operations["PublicEventTypes_availability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Сетка слотов конкретного дня со статусами free/busy —
         *     панель «Статус слотов» справа от календаря.
         */
        get: operations["PublicEventTypes_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Публичный профиль владельца для шапки каталога и страницы бронирования. */
        get: operations["PublicOwner_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Календарь доступности на окно записи — данные для месячной сетки. */
        AvailabilityCalendar: {
            eventTypeId: string;
            timeZone: string;
            /**
             * Format: date
             * @description Первый день окна записи (сегодня в таймзоне владельца).
             */
            windowStart: string;
            /**
             * Format: date
             * @description Последний день окна: windowStart + 14 дней.
             */
            windowEnd: string;
            /** @description Дни окна по возрастанию. Дни вне окна в ответ не попадают. */
            days: components["schemas"]["DayAvailability"][];
        };
        /** @description Созданное бронирование. */
        Booking: {
            id: string;
            eventTypeId: string;
            /**
             * @description Название типа события на момент бронирования — чтобы список встреч
             *     владельца читался без дополнительных запросов и не ломался,
             *     если тип события переименовали или удалили.
             */
            eventTypeTitle: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            guest: components["schemas"]["Guest"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Запрос на бронирование. end не передаётся: выводится из типа события. */
        BookingCreate: {
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало выбранного слота, UTC. Должно совпадать со слотом сетки в статусе free.
             */
            start: string;
            guest: components["schemas"]["Guest"];
        };
        ConflictError: {
            /** @enum {string} */
            code: "slot_taken" | "event_type_already_exists";
            message: string;
        };
        /** @description Сводка по одному дню месяца — для подписей вида «36 св.» в календаре. */
        DayAvailability: {
            /** Format: date */
            date: string;
            /**
             * Format: int32
             * @description Сколько слотов дня свободно.
             */
            freeSlots: number;
            /**
             * Format: int32
             * @description Сколько слотов в сетке дня всего.
             */
            totalSlots: number;
            /**
             * @description false, если день вне окна записи или свободных слотов нет —
             *     фронтенд делает такой день некликабельным.
             */
            isBookable: boolean;
        };
        /**
         * @description Сетка слотов за один день — панель «Статус слотов».
         *     Возвращаются и свободные, и занятые слоты, чтобы гость видел загруженность дня.
         */
        DaySlots: {
            eventTypeId: string;
            /**
             * Format: date
             * @description Запрошенная дата в таймзоне владельца.
             */
            date: string;
            /** @description Таймзона, в которой фронтенд форматирует время. */
            timeZone: string;
            /** @description Все слоты дня по возрастанию start. Пустой массив — выходной или день вне окна. */
            slots: components["schemas"]["Slot"][];
        };
        /** @description Тип события — шаблон встречи, которую можно забронировать. */
        EventType: {
            /** @description Человекочитаемый идентификатор-слаг, задаёт владелец. */
            id: string;
            title: string;
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах. Она же — шаг сетки слотов.
             */
            durationMinutes: number;
        };
        /** @description Данные для создания типа события. */
        EventTypeCreate: {
            id: string;
            title: string;
            /** @default  */
            description: string;
            /**
             * Format: int32
             * @default 30
             */
            durationMinutes: number;
        };
        /** @description Частичное обновление типа события. id неизменяем. */
        EventTypeUpdate: {
            title?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        /** @description Контактные данные гостя. */
        Guest: {
            name: string;
            /** Format: email */
            email: string;
            /** @description Дополнительные заметки к встрече. */
            notes?: string;
        };
        NotFoundError: {
            /** @enum {string} */
            code: "event_type_not_found" | "booking_not_found";
            message: string;
        };
        /** @description Профиль владельца календаря. Единственный, создаётся при инициализации. */
        Owner: {
            /** @description Отображаемое имя в шапке страницы бронирования. */
            name: string;
            /** @description Короткое описание/приветствие для гостя. */
            bio?: string;
            /**
             * Format: uri
             * @description URL аватара. Если пусто — фронтенд рисует плейсхолдер.
             */
            avatarUrl?: string;
            /** @description Таймзона владельца в формате IANA, например "Europe/Berlin". */
            timeZone: string;
            /**
             * Format: time
             * @description Начало рабочего дня в таймзоне владельца.
             */
            workdayStart: string;
            /**
             * Format: time
             * @description Конец рабочего дня в таймзоне владельца.
             */
            workdayEnd: string;
        };
        /** @description Публичное представление типа события: карточка в каталоге. */
        PublicEventType: {
            id: string;
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Интервал сетки конкретного дня. */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота, UTC.
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота, UTC. start + durationMinutes типа события.
             */
            end: string;
            status: components["schemas"]["SlotStatus"];
        };
        /**
         * @description Статус слота в сетке.
         * @enum {string}
         */
        SlotStatus: "free" | "busy";
        ValidationError: {
            /** @enum {string} */
            code: "invalid_payload" | "slot_not_on_grid" | "slot_outside_window";
            message: string;
            details?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    OwnerBookings_list: {
        parameters: {
            query?: {
                /** @description Нижняя граница выборки, UTC. По умолчанию — текущий момент. */
                from?: string;
                /** @description Верхняя граница выборки, UTC. По умолчанию — без ограничения. */
                to?: string;
                /** @description Фильтр по типу события. По умолчанию — все типы. */
                eventTypeId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    OwnerBookings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerBookings_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    OwnerEventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    OwnerEventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerEventTypes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerEventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    OwnerProfile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
    PublicBookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    PublicBookings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    PublicEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventType"][];
                };
            };
        };
    };
    PublicEventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    PublicEventTypes_availability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityCalendar"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    PublicEventTypes_slots: {
        parameters: {
            query: {
                /** @description Дата в таймзоне владельца. Обязательна: слоты запрашиваются по дню. */
                date: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySlots"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    PublicOwner_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
}
